# Generated by Django 4.0.3 on 2022-03-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='total_views',
            field=models.CharField(max_length=10000),
        ),
    ]
