# Generated by Django 4.0.3 on 2022-04-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_contact_contacted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_ready_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
