# Generated by Django 4.0.3 on 2022-03-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blog_reviwewd_by_blog_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
