# Generated by Django 4.0.3 on 2022-03-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='total_views',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
