# Generated by Django 4.0.3 on 2022-04-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
