# Generated by Django 4.0.3 on 2022-03-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_profile_facebook_url_profile_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePicture',
            field=models.ImageField(blank=True, default='img/blog-assests/default-profile-img.svg', null=True, upload_to='img/blog-assests/profile-pictures/'),
        ),
    ]
