# Generated by Django 4.0.3 on 2022-04-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_contact_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/blog-assests/profile-pictures/'),
        ),
    ]
