# Generated by Django 4.0.3 on 2022-04-05 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_profile_profilepicture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='upload_to',
            new_name='updated_at',
        ),
    ]
