# Generated by Django 4.0.3 on 2022-04-06 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_subscriptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriptions',
            new_name='Subscription',
        ),
    ]
