# Generated by Django 4.0.3 on 2022-03-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.CharField(max_length=256)),
                ('total_likes', models.CharField(max_length=256)),
            ],
        ),
    ]
